#redis集群
server:
  port: 8080

spring:
  application:
    name: springboot-redis-cluster
  #redis集群信息
  redis:
    password:
    cluster:
      nodes:
        - localhost:7000
      max-redirects: 3
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        #连接池最大阻塞等待时间（使用负值表示没有限制） 
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
    timeout: 1000

        
#-----------------------------------日志--------------------------------------------------------
logging:
  level:
    com.cht.springboot.redis.cluster.mapper : debug
   
    
    